services:
  server:
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - db-password
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    build:
      context: .
      target: final
    ports:
      - 9013:9013
    develop:
      watch:
        - path: .
          action: rebuild

  db:
    image: postgres
    restart: always
    secrets:
      - db-password
    volumes:
      - cogmote:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${POSTGRES_USER}", "-U", "${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  cogmote:
secrets:
  db-password:
    file: db/password.txt
